### DISCUSSION TITLE
How to host using traefik

### DISCUSSION THREAD

**Discussion by bpawnzZ** [ItzCrazyKns/Vane#457] [General]
Hello all.  Took me a lil bit to get it right but if anyone is interested this how to successfully host this to the internet using traefik as reverse proxy.  I personally have this behind cloudflare safe access for my access control. But this works perfectly and isn't well explained really anywhere.  Hope this helps someone.  

Note: The fact i am joining existing network 'caddy_default' is because i was previously using Caddy and everything was already setup on that network.. just not trying to throw anyone off.  

Below setup and clean build and you are good to go.
```
docker compose build --no-cache
docker compose up -d
```
```
version: '3.7'

services:
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - 4000:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.searxng.entrypoints=websecure"
      - "traefik.http.routers.searxng.rule=Host(`searxng.example.com`)"  # Use of placeholder domain
      - "traefik.http.routers.searxng.tls.certresolver=letsencrypt"
      - "traefik.http.services.searxng.loadbalancer.server.port=8080"
    networks:
      caddy_default:
        ipv4_address: 169.69.0.192
    restart: unless-stopped

  perplexica-backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    image: itzcrazykns1337/perplexica-backend:main
    environment:
      - SEARXNG_API_URL=http://169.69.0.192:8080  # Example URL
    ports:
      - 3001:3001
    volumes:
      - backend-dbstore:/home/perplexica/data
      - ./config.toml:/home/perplexica/config.toml
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      caddy_default:
        ipv4_address: 169.69.0.238
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.perplexica-ws.entrypoints=websecure"
      - "traefik.http.routers.perplexica-ws.rule=Host(`perplexica.example.com`) && PathPrefix(`/api`)"  # Use of placeholder domain
      - "traefik.http.routers.perplexica-ws.tls.certresolver=letsencrypt"
      - "traefik.http.services.perplexica-ws.loadbalancer.server.port=3001"
      - "traefik.http.middlewares.perplexica-ws.headers.customrequestheaders.X-Forwarded-Proto=https"

  perplexica-frontend:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=https://perplexica.example.com/api  # Use of placeholder domain
        - NEXT_PUBLIC_WS_URL=wss://perplexica.example.com/api  # Use of placeholder domain
    image: itzcrazykns1337/perplexica-frontend:main
    depends_on:
      - perplexica-backend
    ports:
      - 3000:3000
    networks:
      caddy_default:
        ipv4_address: 169.69.0.239
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.perplexica.entrypoints=websecure"
      - "traefik.http.routers.perplexica.rule=Host(`perplexica.example.com`)"  # Use of placeholder domain
      - "traefik.http.routers.perplexica.tls.certresolver=letsencrypt"
      - "traefik.http.services.perplexica.loadbalancer.server.port=3000"

networks:
  caddy_default:
    external: true

volumes:
  backend-dbstore:
  ```
